permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Zamani Visuals"
  description: |
    Personal portfolio website containing case studies and client work.
  font_url: "https://use.typekit.net/oqt0wba.css"
  rationales:
    typefaces.primary: |
      paralucent is the primary typeface used for this website. It's bold and legibale in a smaller font size. Headers and links should ony be used as uppercase. Only paragraph content should be in lowercase.
    typefaces.secondary: |
      roboto mono is the secondary typeface. It is used for links in the navigation bar and single text links.
    color.primary: |
      This is the primary colour. It should be used as main headers.
    color.primary.dark: |
      This colour is for the main text.
    color.primary.light: |
      This is the colour for the background.
    color.primary.accent: |
      This colour is for link hovers and for secondary text headers.
