title: "Navigation"
description: |
    This is the top nav and it sits at the top of every page. It has the links to the other pages of the site.
patterns :
  navigation:
    title: "Top Nav"
    description: |
      This should go at the top of every page.
    color: black;
